name: Release Docker Image
on:
  push:
    branches: [ release_docker, dev-build ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
env:
  ORG: timescale #timescaledev
  TS_VERSION: ${{ github.event.inputs.version || '2.5.0' }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:

  # Build multi-arch TimescaleDB images for both TSL and OSS code.
  timescaledb:

    name: PG${{ matrix.pg }}${{ matrix.oss }}
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    strategy:
      fail-fast: false
      matrix:
        pg: [12, 13, 14]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    #- name: Build and push multi-platform Docker image for TimescaleDB
    #  run: make multi ORG=$ORG PG_VER=pg${{ matrix.pg }} TS_VERSION=$TS_VERSION

    #- name: Build and push Docker image
    #  uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
    #  with:
    #    context: .
    #    push: true
    #    tags: ${{ steps.meta.outputs.tags }}
    #    labels: ${{ steps.meta.outputs.labels }}

