name: Release Docker Image
on:
  push:
    branches: [ release_docker, dev-build ]
  workflow_dispatch:
    inputs:
      ts_version:
        description: 'Timescale version to release'
        required: true
      pgis_version:
        description: 'Postgis version to release'
        required: false
env:
  TS_VERSION: ${{ github.event.inputs.ts_version || '2.5.0' }}
  PGIS_VERSION: ${{ github.event.inputs.pgis_version || '2.5.5' }}
  REGISTRY: ghcr.io
  IMAGE_NAME: innofreight/timescaledb-postgis-${{ github.event.inputs.version || '2.5.0' }}
jobs:

  # Builds image, which extends TimescaleDB image with PostGIS. Thus it depends on the job timescaledb.
  # The images are built only for amd64. Support for 32-bit needs to be investigated.
  # The images are built on top of TSL version only.
  timescaledb-postgis:

    name: PG${{ matrix.pg }}-postgis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pg: [ 14 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: postgis
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            POSTGIS_VERSION=${{ env.PGIS_VERSION }}
            PG_VERSION_TAG=${{ matrix.pg }}
            TS_VERSION=${{ env.TS_VERSION }}